reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_empty_files: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!**/*.md"
    - "**/*.py"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/Dockerfile"
  path_instructions:
    - path: "**/*.py"
      instructions: "Focus on security, performance, and Python best practices"
    - path: "**/Dockerfile"
      instructions: "Check for security vulnerabilities and optimization opportunities"
    - path: "**/*.yml"
      instructions: "Validate Docker Compose syntax and security"
chat:
  auto_reply: true